apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  labels:
    app: payments-api
spec:
  type: LoadBalancer
  selector:
    app: payments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80