package com.techchallenge.payments.entities

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.math.BigDecimal


@DynamoDBTable(tableName = "Payments")
data class Payment(
    @DynamoDBAutoGeneratedKey
    private val id: String,

    @DynamoDBHashKey
    @DynamoDBAttribute
    private val orderId: String,

    @DynamoDBAttribute
    private val paymentType: String,

    @DynamoDBAttribute
    private val amount: BigDecimal
) {
}
