name: SonarQube Analysis

on:
  push:
    branches:
      - feature/*

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Install Dependencies
        run: ./gradlew clean build -x test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=https://sonarcloud.io/summary/overall?id=Tech-Challenge-7SOAT_payments \
            -Dsonar.login=$SONAR_TOKEN
